import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [walletAddress, setWalletAddress] = useState();

  let metamask = typeof window !== "undefined" && window.ethereum;
  let phantom = typeof window !== "undefined" && window.solana;

  const connectMeta = async () => {
    try {
      if (!metamask) return alert("Please Install MetaMask");

      const accounts = await metamask.request({
        method: "eth_requestAccounts",
      });

      if (accounts.length) {
        setWalletAddress(accounts[0]);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const connectPhantom = async () => {
    try {
      if (!phantom) return alert("Please Install Phantom");

      const resp = await window.solana.connect();

      if (resp) {
        const publicAddress = `0x${resp.publicKey.toString()}`;
        setWalletAddress(publicAddress);
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className="app">
      <Head>
        <title>Wallet Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="h1">Welcome to WEB 3.0</h1>

      <h3>{walletAddress}</h3>

      <button
        className="btn"
        onClick={connectMeta}
        disabled={walletAddress ? true : false}
      >
        <Image src="/meta.png" alt="metamask" width={30} height={30} />
        <p>Connect your Metamask</p>
      </button>

      <button
        className="btn"
        onClick={connectPhantom}
        disabled={walletAddress ? true : false}
      >
        <Image src="/phantom.png" alt="metamask" width={35} height={35} />
        <p>Connect your Phantom</p>
      </button>
    </div>
  );
}
